/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extratutioncenter;

import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shiva
 */
public class ExtraTutionCenter extends javax.swing.JFrame {
 
    /**
     * Creates new form ExtraTutionCenter
     */
    public ExtraTutionCenter() {
        initComponents();
        jLabel3.setVisible(false);
        studentsdrpdwn.setVisible(false);
        jTextArea1.setVisible(false);
        jLabel4.setVisible(false);
        jLabel6.setVisible(false);
    }
    UserData UD=new UserData();
    StudentFrame sf=new StudentFrame();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String username;
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AccessBookStorebtn = new javax.swing.JButton();
        LessonsTaughtHIstorybtn = new javax.swing.JButton();
        viewStudentProfilebtn = new javax.swing.JButton();
        logutbtn = new javax.swing.JButton();
        printReportbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        studentsdrpdwn = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        libraryRecordtable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Admin Portal");

        AccessBookStorebtn.setText("Access Book Store");
        AccessBookStorebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessBookStorebtnActionPerformed(evt);
            }
        });

        LessonsTaughtHIstorybtn.setText("Lessons Taught");
        LessonsTaughtHIstorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonsTaughtHIstorybtnActionPerformed(evt);
            }
        });

        viewStudentProfilebtn.setText("Student Profile");
        viewStudentProfilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentProfilebtnActionPerformed(evt);
            }
        });

        logutbtn.setText("LogOut");
        logutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logutbtnActionPerformed(evt);
            }
        });

        printReportbtn.setText("Print Report");
        printReportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReportbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Report has Lessons booked by student,  (attended, missed, cancelled), Books Ordered");

        studentsdrpdwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsdrpdwnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Select Student");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        libraryRecordtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(libraryRecordtable);

        jLabel6.setText("Books Ordered By Student");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AccessBookStorebtn)
                                .addGap(46, 46, 46)
                                .addComponent(LessonsTaughtHIstorybtn)
                                .addGap(55, 55, 55)
                                .addComponent(viewStudentProfilebtn)
                                .addGap(48, 48, 48)
                                .addComponent(printReportbtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)
                                .addComponent(studentsdrpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel5)))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logutbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(66, 66, 66)))))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccessBookStorebtn)
                            .addComponent(LessonsTaughtHIstorybtn)
                            .addComponent(viewStudentProfilebtn)
                            .addComponent(printReportbtn))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logutbtn)
                            .addComponent(jLabel2)))
                    .addComponent(studentsdrpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logutbtnActionPerformed
        // TODO add your handling code here:
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
    }//GEN-LAST:event_logutbtnActionPerformed

    private void AccessBookStorebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessBookStorebtnActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        jLabel5.setVisible(false);
        studentsdrpdwn.setVisible(false);
        jTextArea1.setVisible(false);
        jLabel6.setVisible(true);
        jLabel6.setText("Books Available in the Store");
        DefaultTableModel model1= (DefaultTableModel) libraryRecordtable.getModel();
        CGPBookStore cgp=new CGPBookStore();
            libraryRecordtable.setVisible(true);
            model1.setRowCount(0);
            for(String key1:CGPBookStore.subjectMap.keySet()){
                model1.addRow(new Object[]{key1, CGPBookStore.subjectMap.get(key1)});
            }
            System.out.println("\nBooks Stock is 100 per subject by default");
            System.out.println("\nBooks Available in the store are :");
            
            CGPBookStore.subjectMap.entrySet().forEach(entry->{
                System.out.println(entry.getKey() + " = " + entry.getValue());  
            });
            
            System.out.println("\n");
            
//            System.out.println(Collections.singletonList(CGPBookStore.subjectMap)+"\n\n");
    }//GEN-LAST:event_AccessBookStorebtnActionPerformed

    private void studentsdrpdwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsdrpdwnActionPerformed
        // TODO add your handling code here:
        jLabel5.setVisible(false);
        jTextArea1.setVisible(true);
        String name=studentsdrpdwn.getSelectedItem().toString();        
//        System.out.println("****"+name+"****");
//        System.out.print((UD.getProfile().get(name)));
        jTextArea1.setText((allUserDetails.get(name)).toString());
        UserData data = (UserData)UD.getProfile().get(name.trim());
        List<BooksBooked> bookings = data.getBookBooked();
        DefaultTableModel model1= (DefaultTableModel) libraryRecordtable.getModel();
        model1.setRowCount(0);
        Object rowData[]=new Object[2];
        if(bookings != null){
            libraryRecordtable.setVisible(true);
            for(int i=0;i<bookings.size();i++){
                rowData[0]=bookings.get(i).Subject;
                rowData[1]=bookings.get(i).quantity;
                model1.addRow(rowData);
            }
        }
        else
        {
            libraryRecordtable.setVisible(false);
        }
    }//GEN-LAST:event_studentsdrpdwnActionPerformed
    Map<String,Object> allUserDetails = UD.getProfile();
    private void viewStudentProfilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentProfilebtnActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        jLabel6.setVisible(true);
        studentsdrpdwn.setVisible(true);
        jLabel4.setVisible(false);
        jLabel6.setText("Books Ordered by Student");
        Set<String> allKeys = UD.getProfile().keySet();
        for(String key:allKeys)
        {
            studentsdrpdwn.addItem(key);
        }    
    }//GEN-LAST:event_viewStudentProfilebtnActionPerformed

    private void LessonsTaughtHIstorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonsTaughtHIstorybtnActionPerformed
        jLabel3.setVisible(false);
        jLabel6.setVisible(false);
        studentsdrpdwn.setVisible(false);
        jTextArea1.setVisible(false);
        libraryRecordtable.setVisible(false);
        jLabel4.setVisible(false);
        System.out.println("Lessons Booking History");
        String historyreport=" Booked = "+getStatsofBookings().get("Booked")+" \nAttended = "+getStatsofBookings().get("Attended")+" \nMissed = "+getStatsofBookings().get("Missed")+" \nCancelled = "+getStatsofBookings().get("Cancelled");
        System.out.println(historyreport);

        jLabel5.setText(historyreport);

    }//GEN-LAST:event_LessonsTaughtHIstorybtnActionPerformed

    private void printReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReportbtnActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        studentsdrpdwn.setVisible(false);
        jTextArea1.setVisible(false);
        libraryRecordtable.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_printReportbtnActionPerformed

    private Map<String,Integer> getStatsofBookings(){
        Map<String,Integer> stats = new HashMap<>();
        stats.put("Booked", 0);
        stats.put("Cancelled", 0);
        stats.put("Attended", 0);
        stats.put("Missed", 0);
        
        Collection<Object> allKeys = UD.getProfile().values();
        UserData tmp = null;
        for(Object val:allKeys)
        {
           tmp = (UserData)val;
           if(tmp.getBooking() != null){
               for(Booking b: tmp.getBooking()){
                   stats.put(b.getStatus(), stats.get(b.getStatus())+1);
                   if(!"Booked".equals(b.getStatus())){
                    stats.put("Booked", stats.get("Booked")+1);
                   }
               }
           }
        }
        return stats;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtraTutionCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtraTutionCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtraTutionCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtraTutionCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccessBookStorebtn;
    private javax.swing.JButton LessonsTaughtHIstorybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable libraryRecordtable;
    private javax.swing.JButton logutbtn;
    private javax.swing.JButton printReportbtn;
    private javax.swing.JComboBox<String> studentsdrpdwn;
    private javax.swing.JButton viewStudentProfilebtn;
    // End of variables declaration//GEN-END:variables
}
