/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extratutioncenter;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author shiva
 */
public class StudentFrame extends javax.swing.JFrame {
    
public static int engCompCount = 10,engWritingCount=10,mathCount = 10,numericReasoningCount=10,
        verbalReasoningCount=10,nonVerbalReasoningCount=10;//,sub7Count=10,sub8Count=10,sub9Count=10,sub10Count=10,sub11Count=11,sub12Count=12;


    /**
     * Creates new form StudentFrame
     */
    //MainPage mp=new MainPage();

    private UserData ud=new UserData();

    
    public String username;
    public int Bookings,Attended,Missed,Cancelled;

    public int getBookings() {
        return Bookings;
    }

    public void setBookings(int Bookings) {
        this.Bookings = Bookings;
    }

    public int getAttended() {
        return Attended;
    }

    public void setAttended(int Attended) {
        this.Attended = Attended;
    }

    public int getMissed() {
        return Missed;
    }

    public void setMissed(int Missed) {
        this.Missed = Missed;
    }

    public int getCancelled() {
        return Cancelled;
    }

    public void setCancelled(int Cancelled) {
        this.Cancelled = Cancelled;
    }

    public StudentFrame() {
       
        initComponents();
        newCOmp();
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void newCOmp()
    {
        jComboBox1.setVisible(false);
        jButton6.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jList1.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jList1.setModel(new DefaultListModel());
        jTable1.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jButton8.setVisible(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 600));

        jButton1.setText("View Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Student Portal");

        jButton2.setText("Book Lessons");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View Bookings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modify Slot");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Tutor1", "Tutor2", "Tutor3", "Tutor4", "Tutor5", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "English Comprehension", "English Writing", "Maths", "Numerical Reasoning", "Verbal Reasoning", "Non-Verbal Reasoning", "Subject7", "Subject8", "Subject9", "Subject10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton6.setText("Book");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Order Books");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setName("SubjectNameLabel"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Select Tutor");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Select Subject");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tutor", "Subject", "TimeSlot", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(353, 353, 353)
                                .addComponent(jLabel1)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(36, 36, 36)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel6))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jButton8)))
                                        .addGap(46, 46, 46)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addContainerGap(135, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addGap(0, 0, Short.MAX_VALUE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4)
                                .addContainerGap(70, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:        
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    Map<String,Object> allUserDetails = ud.getProfile();
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Your booking for "+jComboBox1.getSelectedItem().toString()+","+jList1.getSelectedValue()+" is successful");
        //bookingsCount++;
        ud.setSessionsBooked(ud.getSessionsBooked()+1);
        //counter.setBookingCounter(bookingsCount);
        //setBookings(getBookings()+1);
        String user=getUsername();
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String timeslot = myDateObj.format(myFormatObj); 
        Booking b1= new Booking(jComboBox1.getSelectedItem().toString(),jList1.getSelectedValue(),timeslot,"Booked");
        UserData userdata=(UserData)allUserDetails.get(user);
        List<Booking> bookings = userdata.getBooking();
        if(bookings == null){
            bookings = new ArrayList<Booking>();
        }
        bookings.add(b1);
        userdata.setBooking(bookings);
        
        jLabel4.setText(jComboBox1.getSelectedItem().toString());
        if(jList1.getSelectedValue().equalsIgnoreCase("English Comprehension")){
            engCompCount--;
            ud.setSessionsBooked(ud.getSessionsBooked()+1);
            jLabel3.setText("Available slots for "+jList1.getSelectedValue()+" are "+engCompCount);
            System.out.println("Available slots for "+jList1.getSelectedValue()+" are "+engCompCount);
            //System.out.print(engCompCount);
        }else if(jList1.getSelectedValue().equalsIgnoreCase("English Writing")){
            engWritingCount--;
            ud.setSessionsBooked(ud.getSessionsBooked()+1);
            jLabel3.setText("Available slots for "+jList1.getSelectedValue()+" are "+engWritingCount);
            System.out.println("Available slots for "+jList1.getSelectedValue()+" are "+engWritingCount);
        }else if(jList1.getSelectedValue().equalsIgnoreCase("Maths")){
            mathCount--;
            ud.setSessionsBooked(ud.getSessionsBooked()+1);
            jLabel3.setText("Available slots for "+jList1.getSelectedValue()+" are "+mathCount);
            System.out.println("Available slots for "+jList1.getSelectedValue()+" are "+mathCount);
        }else if(jList1.getSelectedValue().equalsIgnoreCase("Numerical Reasoning")){
            numericReasoningCount--;
            ud.setSessionsBooked(ud.getSessionsBooked()+1);
            jLabel3.setText("Available slots for "+jList1.getSelectedValue()+" are "+numericReasoningCount);
            System.out.println("Available slots for "+jList1.getSelectedValue()+" are "+numericReasoningCount);
        }else if(jList1.getSelectedValue().equalsIgnoreCase("verbal Reasoning")){
            verbalReasoningCount--;
            ud.setSessionsBooked(ud.getSessionsBooked()+1);
            jLabel3.setText("Available slots for "+jList1.getSelectedValue()+" are "+verbalReasoningCount);
            System.out.println("Available slots for "+jList1.getSelectedValue()+" are "+verbalReasoningCount);
        }else if(jList1.getSelectedValue().equalsIgnoreCase("Non-Verbal Reasoning")){
            nonVerbalReasoningCount--;
            ud.setSessionsBooked(ud.getSessionsBooked()+1);
            jLabel3.setText("Available slots for "+jList1.getSelectedValue()+" are "+nonVerbalReasoningCount);
            System.out.println("Available slots for "+jList1.getSelectedValue()+" are "+nonVerbalReasoningCount);
        }
        String tutor1=jComboBox1.getSelectedItem().toString();
        String subject1=jList1.getSelectedValue();
        System.out.println("Booking with "+tutor1+" for  "+subject1+" is Booked at "+timeslot+" Successfully");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setVisible(true);
        jLabel5.setVisible(true);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
         
        //making jlist visible on click of view bookings
        jList1.setVisible(false);
        
            //showing only tutor1 list values at beginning as it is by default selected
            DefaultListModel defaultListModel = new DefaultListModel();
            defaultListModel.addElement("English Comprehension");
            defaultListModel.addElement("English Writing");
            defaultListModel.addElement("Maths");
            jList1.setModel(defaultListModel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        DefaultListModel defaultListModel = new DefaultListModel();
    switch (jComboBox1.getSelectedIndex()) {
        case 0:
            jLabel3.setVisible(false);
            jLabel6.setVisible(false);
            jList1.setVisible(false);
            jButton6.setVisible(false);
            break;
        case 1:
            defaultListModel.addElement("English Comprehension");
            defaultListModel.addElement("English Writing");
            defaultListModel.addElement("Maths");
            jList1.setModel(defaultListModel);
            jLabel6.setVisible(true);
            jList1.setVisible(true);
            jButton6.setVisible(true);
            break;
        case 2:
            defaultListModel.addElement("Numerical Reasoning");
            defaultListModel.addElement("Verbal Reasoning");
            defaultListModel.addElement("Non-Verbal Reasoning");
            jList1.setModel(defaultListModel);
            jLabel6.setVisible(true);
            jList1.setVisible(true);
            jButton6.setVisible(true);
            break;
        case 3:
            defaultListModel.addElement("Maths");
            defaultListModel.addElement("English Comprehension");
            defaultListModel.addElement("Non-Verbal Reasoning");
            jList1.setModel(defaultListModel);
            jLabel6.setVisible(true);
            jList1.setVisible(true);
            jButton6.setVisible(true);
            break;
        case 4:
            defaultListModel.addElement("English Writing");
            defaultListModel.addElement("Verbal Reasoning");
            defaultListModel.addElement("Maths");
            jList1.setModel(defaultListModel);
            jLabel6.setVisible(true);
            jList1.setVisible(true);
            jButton6.setVisible(true);
            break;
        case 5:
            defaultListModel.addElement("English Comprehension");
            defaultListModel.addElement("Numerical Reasoning");
            defaultListModel.addElement("English Writing");
            jList1.setModel(defaultListModel);
            jLabel6.setVisible(true);
            jList1.setVisible(true);
            jButton6.setVisible(true);
            break;
        default:
            break;
    }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jList1.setVisible(false);
        jComboBox1.setVisible(false);
        jLabel3.setVisible(false);
        String user=getUsername();
//        System.out.println(name);
        JFrame jFrame = new JFrame("View Profile");
//        JLabel nameLabel = new JLabel();
//        JLabel nameValue = new JLabel();
        JTextArea profiledata= new JTextArea();
        profiledata.setEditable(false);
        profiledata.setText((allUserDetails.get(user)).toString());
//        nameLabel.setText("Name: ");
//        nameValue.setText(allUserDetails.get(name).toString());//------------------------------------------------focus here to print onto another panel
        System.out.println("MyProfile\n"+allUserDetails.get(user).toString());
        
        UserData userdata=(UserData)allUserDetails.get(user);
        ud.getBooking();
        
//        System.out.println("and My Sessions Bookings Details \n");
        JPanel jPanel = new JPanel();
//        jPanel.add(nameLabel);
//        jPanel.add(nameValue);
        jPanel.add(profiledata);
        jPanel.setBackground(Color.red);
        
        jFrame.add(jPanel);
        jFrame.setSize(300,300);
        jFrame.show();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        jButton6.setVisible(false);
        if(!evt.getValueIsAdjusting()){
            JList source = (JList) evt.getSource();
            
            if(source!=null){
            if(source.getSelectedValue()!=null && source.getSelectedValue().toString().equalsIgnoreCase("English Comprehension")){
                jLabel3.setVisible(true);
                jLabel3.setText("Available slots for "+source.getSelectedValue().toString()+" are "+engCompCount);
//                System.out.println(source.getSelectedValue().toString());
                jButton6.setVisible(true);
            }else if(source.getSelectedValue()!=null && source.getSelectedValue().toString().equalsIgnoreCase("English Writing")){
                jLabel3.setVisible(true);
                jLabel3.setText("Available slots for "+source.getSelectedValue().toString()+" are "+engWritingCount);
//                System.out.println(source.getSelectedValue().toString());
                jButton6.setVisible(true);
            }else if(source.getSelectedValue()!=null && source.getSelectedValue().toString().equalsIgnoreCase("Maths")){
                jLabel3.setVisible(true);
                jLabel3.setText("Available slots for "+source.getSelectedValue().toString()+" are "+mathCount);
//                System.out.println(source.getSelectedValue().toString());
                jButton6.setVisible(true);
            }else if(source.getSelectedValue()!=null && source.getSelectedValue().toString().equalsIgnoreCase("Numerical Reasoning")){
                jLabel3.setVisible(true);
                jLabel3.setText("Available slots for "+source.getSelectedValue().toString()+" are "+numericReasoningCount);
//                System.out.println(source.getSelectedValue().toString());
                jButton6.setVisible(true);
            }else if(source.getSelectedValue()!=null && source.getSelectedValue().toString().equalsIgnoreCase("Verbal Reasoning")){
                jLabel3.setVisible(true);
                jLabel3.setText("Available slots for "+source.getSelectedValue().toString()+" are "+verbalReasoningCount);
//                System.out.println(source.getSelectedValue().toString());
                jButton6.setVisible(true);
            }else if(source.getSelectedValue()!=null && source.getSelectedValue()!=null && source.getSelectedValue().toString().equalsIgnoreCase("Non-Verbal Reasoning")){
                jLabel3.setVisible(true);
                jLabel3.setText("Available slots for "+source.getSelectedValue().toString()+" are "+nonVerbalReasoningCount);
//                System.out.println(source.getSelectedValue().toString());
                jButton6.setVisible(true);
            }
         }
        }        
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.out.print(username);
        CGPBookStore BS= new CGPBookStore(username);
        BS.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String user=getUsername();
        UserData userdata=(UserData)allUserDetails.get(user);
        List<Booking> bookings = userdata.getBooking();
        jTable1.setVisible(true);
        DefaultTableModel model1= (DefaultTableModel) jTable1.getModel();
        model1.setRowCount(0);
        Object rowData[]=new Object[4];
        if(bookings != null){
            for(int i=0;i<bookings.size();i++){
                rowData[0]=bookings.get(i).tutor;
                rowData[1]=bookings.get(i).subject;
                rowData[2]=bookings.get(i).timeslot;
                rowData[3]=bookings.get(i).Status;
                model1.addRow(rowData);
            }
        }                  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTable1.setVisible(false);      
        jLabel6.setVisible(false);
        jList1.setVisible(false);
        jButton6.setVisible(false);
        DefaultComboBoxModel model=(DefaultComboBoxModel) jComboBox2.getModel();
        //model.removeAllElements();        
        String user=getUsername();
        UserData userdata=(UserData)allUserDetails.get(user);
        List<Booking> b=userdata.getBooking();
        if(b!=null){
            for(int i=0;i<b.size();i++){
                if((b.get(i).Status.equals("Booked"))){
                    jComboBox2.addItem((b.get(i).tutor));
                    jComboBox2.setVisible(true);
                }
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:              
        DefaultComboBoxModel model=(DefaultComboBoxModel) jComboBox3.getModel();
        model.removeAllElements();
        String user=getUsername();
        UserData userdata=(UserData)allUserDetails.get(user);
        List<Booking> b=userdata.getBooking();
        if(b!=null){
            for(int i=0;i<b.size();i++){
                if(b.get(i).Status.equals("Booked")&&b.get(i).tutor.equals(jComboBox2.getSelectedItem().toString()))
                jComboBox3.addItem(b.get(i).subject);
            }
            jComboBox3.setVisible(true);  
        }
        else
            jButton8.setVisible(false);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String student=getUsername();
        UserData user = (UserData) allUserDetails.get(student);
        List<Booking> bookings = user.getBooking();
        
        TableModel model = jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {   
            //System.out.println(model.getRowCount());
            if (model.getValueAt(i, 0) == null) {
                System.out.println("no record");
            }
            else
            {
                //System.out.println("Tutor Name is :" + model.getValueAt(i, 0));
                if(model.getValueAt(i,0)!=null && model.getValueAt(i, 0).equals(jComboBox2.getSelectedItem().toString())){
                    if(model.getValueAt(i, 1).equals(jComboBox3.getSelectedItem().toString()))
                    {
                        bookings.get(i).setStatus("Cancelled");   
//                        ud.setCancelled(ud.getCancelled()+1);
//                        setCancelled(getCancelled()+1);
                        if(jComboBox3.getSelectedItem().equals("English Comprehension"))
                            engCompCount++;
                        else if(jComboBox3.getSelectedItem().equals("English Writing"))
                            engWritingCount++;
                        else if(jComboBox3.getSelectedItem().equals("Maths"))
                            mathCount++;
                        else if(jComboBox3.getSelectedItem().equals("Non-Verbal Reasoning"))
                            nonVerbalReasoningCount++;
                        else if(jComboBox3.getSelectedItem().equals("Verbal Reasoning"))
                            verbalReasoningCount++;
                        else if(jComboBox3.getSelectedItem().equals("Numerical Reasoning"))
                            numericReasoningCount++;
                        JOptionPane.showMessageDialog(null,"Your booking with "+jComboBox2.getSelectedItem()+" and subject "+jComboBox3.getSelectedItem()+" is Cancelled");    
                        System.out.println("Your booking with "+jComboBox2.getSelectedItem()+" and subject "+jComboBox3.getSelectedItem()+" is Cancelled");
                        jComboBox2.removeItem(model.getValueAt(i, 0));
                        jComboBox3.removeItem(model.getValueAt(i, 1));
                        jButton8.setVisible(false);
//                        cancelCount++;
//                        counter.setCancelCounter(cancelCount);
//                        System.out.println("cancel count is"+cancelCount);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        jButton8.setVisible(true);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
