/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extratutioncenter;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author shiva
 */
public class UserData { 

    /**
     * Creates new form UserData
     */   

    public UserData() {
       // initComponents();
    }
       
    private String name,gender,address;
    private String DOB;
    private long contactNo;
    
    public List<Booking> booking;
    
    public List<Booking> getBooking() {
        return booking;
    }

    public void setBooking(List<Booking> booking) {
        this.booking = booking;
    }
    
    public List<BooksBooked> BookBooked;

    public List<BooksBooked> getBookBooked() {
        return BookBooked;
    }

    public void setBookBooked(List<BooksBooked> BookBooked) {
        this.BookBooked = BookBooked;
    }
    
    private int sessionsBooked=0,attended=0,cancelled=0,missed=0;

    public int getMissed() {
        return missed;
    }

    public void setMissed(int missed) {
        this.missed = missed;
    }

    public int getSessionsBooked() {
        return sessionsBooked;
    }

    public void setSessionsBooked(int sessionsBooked) {
        this.sessionsBooked = sessionsBooked;
    }

    public int getAttended() {
        return attended;
    }

    public void setAttended(int attended) {
        this.attended = attended;
    }

    public int getCancelled() {
        return cancelled;
    }

    public void setCancelled(int cancelled) {
        this.cancelled = cancelled;
    }

    public UserData(String name, String gender, String address, String DOB, long contactNo) {
        this.name = name;
        this.gender = gender;
        this.address = address;
        this.DOB = DOB;
        this.contactNo = contactNo;
        
    }
    
//    public UserData(int sessionsBooked,int attended, int cancelled)
//    {
//        this.sessionsBooked=sessionsBooked;
//        this.attended=attended;
//        this.cancelled=cancelled;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    /**
     * @param args the command line arguments
     */
    
    public static HashMap<String, Object> profile = new HashMap<String, Object>();
    
    public static HashMap<String, String> login = new HashMap<String, String>();

    public HashMap<String,String> getLogin(){

        login.put("Shiva","Shiva");
        login.put("Prashanth","Prashanth");
        login.put("Bhargav","Bhargav");
        login.put("Keshav","Keshav");
        login.put("Pranay","Pranay");
        login.put("Veeresh","Veeresh");
        login.put("Shiva6","Shiva6");
        login.put("Shiva7","Shiva7");
        login.put("Shiva8","Shiva8");
        login.put("Shiva9","Shiva9");
        login.put("Shiva10","Shiva10");
        login.put("Shiva11","Shiva11");
        login.put("Shiva12","Shiva12");
        login.put("Shiva13","Shiva13");
        login.put("Shiva14","Shiva14");
        return login;
    }
                
    public HashMap<String, Object> getProfile() {
     return profile;
    }
    static{
        UserData UD1= new UserData("Shiva","Male","AL109JD","28/03/1995",9100370890L);
        UserData UD2= new UserData("Prashanth","Male","AL109JD","14/03/1995",7842207005L);
        UserData UD3= new UserData("Bhargav","Male","AL109JD","02/04/1994",9440880607L);
        UserData UD4= new UserData("Keshav","Male","AL109JD","15/09/1995",9988745612L);
        UserData UD5= new UserData("Pranay","Male","AL109JD","19/08/1993",7799456123L);
        UserData UD6= new UserData("Veeresh","Male","AL109JD","22/03/1991",7799485223L);
        UserData UD7= new UserData("Shiva6","Male","AL109JD","26/03/1997",7416930444L);
        UserData UD8= new UserData("Shiva7","Male","AL109JD","12/03/1998",784456789L);
        UserData UD9= new UserData("Shiva8","Male","AL109JD","28/03/2000",7534218968L);
        UserData UD10= new UserData("Shiva9","Male","AL109JD","21/07/1994",8459612378L);
        UserData UD11= new UserData("Shiva10","Male","AL109JD","15/03/1995",8886664455L);
        UserData UD12= new UserData("Shiva11","Male","AL109JD","13/03/1993",7745689123L);
        UserData UD13= new UserData("Shiva12","Male","AL109JD","09/03/1995",9988756123L);
        UserData UD14= new UserData("Shiva13","Male","AL109JD","08/05/1996",9966853212L);
        UserData UD15= new UserData("Shiva14","Male","AL109JD","02/03/1993",7458963214L);
        
        List<Booking> LessonsBookings = new ArrayList<>();
        List<Booking> LessonsBookings1 = new ArrayList<>();
        List<Booking> LessonsBookings2 = new ArrayList<>();
        List<Booking> LessonsBookings3 = new ArrayList<>();
        List<Booking> LessonsBookings4 = new ArrayList<>();
        List<Booking> LessonsBookings5 = new ArrayList<>();
        
        Booking b = new Booking("Tutor1","Maths",  "01/12/2019", "Attended");
        Booking b1 = new Booking("Tutor3","English Comprehension",  "02/12/2019", "Cancelled");
        Booking b2 = new Booking("Tutor3","Maths",  "01/12/2019", "Missed");
        Booking b3 = new Booking("Tutor2","Verbal Reasoning",  "01/12/2019", "Missed");
        Booking b4 = new Booking("Tutor3","English Comprehension",  "01/12/2019", "Attended");
        Booking b5 = new Booking("Tutor3","Maths",  "02/12/2019", "Missed");
        Booking b6 = new Booking("Tutor1","Maths",  "04/12/2019", "Booked");
        Booking b7 = new Booking("Tutor3","English Comprehension",  "05/12/2019", "Booked");
        Booking b8 = new Booking("Tutor3","Maths",  "06/12/2019", "Booked");
        Booking b9 = new Booking("Tutor1","Maths",  "07/12/2019", "Missed");
        Booking b10 = new Booking("Tutor3","English Comprehension",  "08/12/2019", "Booked");
        Booking b12 = new Booking("Tutor3","Maths",  "01/12/2019", "Booked");
        Booking b11 = new Booking("Tutor1","Maths",  "08/12/2019", "Cancelled");
        Booking b15 = new Booking("Tutor3","English Comprehension",  "04/12/2019", "Booked");
        Booking b13 = new Booking("Tutor3","Maths",  "02/12/2019", "Attended");
        Booking b14 = new Booking("Tutor1","Maths",  "01/12/2019", "Missed");
        Booking b16 = new Booking("Tutor3","English Comprehension",  "01/12/2019", "Missed");
        Booking b17 = new Booking("Tutor3","Maths",  "01/12/2019", "Booked");
        Booking b18 = new Booking("Tutor1","Maths",  "01/12/2019", "Booked");
        Booking b19 = new Booking("Tutor3","English Comprehension",  "06/12/2019", "Booked");
        Booking b20 = new Booking("Tutor3","Maths",  "01/12/2019", "Booked");
        
        LessonsBookings.add(b);
        LessonsBookings.add(b1);
        LessonsBookings.add(b2);
        LessonsBookings.add(b3);
        LessonsBookings.add(b4);
        
        
        LessonsBookings1.add(b5);
        LessonsBookings1.add(b6);
        LessonsBookings1.add(b7);
        LessonsBookings1.add(b8);
        LessonsBookings1.add(b9);
        
        
        LessonsBookings2.add(b10);
        LessonsBookings2.add(b11);
        LessonsBookings2.add(b12);
        LessonsBookings2.add(b13);
        
        
        LessonsBookings3.add(b14);
        LessonsBookings3.add(b15);
        LessonsBookings3.add(b16);
        
        
        LessonsBookings4.add(b17);
        LessonsBookings4.add(b18);
        LessonsBookings4.add(b19);
        LessonsBookings4.add(b20); 
        
        UD1.setBooking(LessonsBookings);
        UD2.setBooking(LessonsBookings1);
        
        UD3.setBooking(LessonsBookings2);
        
        UD10.setBooking(LessonsBookings2);
        UD10.setBooking(LessonsBookings4);
        
        UD3.setBooking(LessonsBookings3);
        
        
        
        
        
        
        
        List<BooksBooked> BooksOrdered=new ArrayList<>();
        List<BooksBooked> BooksOrdered1=new ArrayList<>();
        List<BooksBooked> BooksOrdered2=new ArrayList<>();
        List<BooksBooked> BooksOrdered3=new ArrayList<>();
        List<BooksBooked> BooksOrdered4=new ArrayList<>();
        
        BooksBooked BB=new BooksBooked("Maths", 6);
        BooksBooked BB1=new BooksBooked("English Comprehension", 9);
        BooksBooked BB2=new BooksBooked("English writing", 7);
        BooksBooked BB3=new BooksBooked("Verbal Reasoning", 9);
        BooksBooked BB4=new BooksBooked("Non-Verbal Reasoning", 4);
        BooksBooked BB5=new BooksBooked("English Comprehension", 7);
        BooksBooked BB6=new BooksBooked("Numerical Reasoning", 6);
        BooksBooked BB7=new BooksBooked("English Comprehension", 5);
        BooksBooked BB8=new BooksBooked("Maths", 6);
        BooksBooked BB9=new BooksBooked("English writing", 9);
        
        BooksOrdered.add(BB);
        BooksOrdered.add(BB1);
        BooksOrdered.add(BB2);
        BooksOrdered.add(BB3);
        
        BooksOrdered1.add(BB3);
        BooksOrdered1.add(BB4);
        
        BooksOrdered2.add(BB5);
        BooksOrdered2.add(BB6);
        
        
        BooksOrdered3.add(BB7);
        BooksOrdered3.add(BB8);
        
        BooksOrdered4.add(BB9);
        BooksOrdered4.add(BB8);
        BooksOrdered4.add(BB6);
        
        
        UD1.setBookBooked(BooksOrdered);
        UD2.setBookBooked(BooksOrdered1);
        UD3.setBookBooked(BooksOrdered2);
        UD4.setBookBooked(BooksOrdered3);
        UD10.setBookBooked(BooksOrdered4);
       
        
        
        
        
        
        
        
        profile.put("Shiva", UD1);
        profile.put("Prashanth", UD2);
        profile.put("Bhargav", UD3);
        profile.put("Shiva3", UD4);
        profile.put("Shiva4", UD5);
        profile.put("Shiva5", UD6);
        profile.put("Shiva6", UD7);
        profile.put("Shiva7", UD8);
        profile.put("Shiva8", UD9);
        profile.put("Shiva9", UD10);
        profile.put("Shiva10", UD11);
        profile.put("Shiva11", UD12);
        profile.put("Shiva12", UD13);
        profile.put("Shiva13", UD14);
        profile.put("Shiva14", UD15);
        

         
    }
    

    @Override
    public String toString()
    {
        String data="Student Name : "+this.name+"\nDate of Birth : "+this.DOB+ " \nGender : "+this.gender+"\nAddress : "+this.address+" \nEmergency Contact Number : "+this.contactNo;
        return data;
    }
}
